group: travis-latest
language: minimal
os: linux

services:
  - docker

notifications:
  email: false

git:
  depth: 1

env:
  matrix:
    - DIMAGE=gcc_5
    - DIMAGE=gcc_6
    - DIMAGE=gcc_7
    - DIMAGE=gcc_8
    - DIMAGE=clang_3.8
    - DIMAGE=clang_4.0
    - DIMAGE=clang_5.0
    - DIMAGE=clang_6.0
    - DIMAGE=clang_7

cache:
  apt: true

branches:
  except:
    - travis-artifacts

matrix:
  fast_finish: true

script:
  - sudo ./build.sh --batch $DIMAGE

